//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterYonetimi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depo
    {
        public string depoId { get; set; }
        public string cihazTuruId { get; set; }
        public string cihazModeliId { get; set; }
        public string envNo { get; set; }
        public string seriNo { get; set; }
        public string garantiBas { get; set; }
        public string durum { get; set; }
        public string islemZaman { get; set; }
        public string islemiYapan { get; set; }
        public string kullanim { get; set; }
        public string aciklama { get; set; }
    }
}
