//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterYonetimi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class envanterTakipWebEntities2 : DbContext
    {
        public envanterTakipWebEntities2()
            : base("name=envanterTakipWebEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Depo> Depo { get; set; }
        public virtual DbSet<Sirket_Lokasyon> Sirket_Lokasyon { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<CihazTuru> CihazTuru { get; set; }
        public virtual DbSet<Islemler> Islemler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Lokasyon> Lokasyon { get; set; }
        public virtual DbSet<Modeller> Modeller { get; set; }
        public virtual DbSet<Modeller_Depo> Modeller_Depo { get; set; }
        public virtual DbSet<Modeller_Islemler> Modeller_Islemler { get; set; }
        public virtual DbSet<Modeller_Saha> Modeller_Saha { get; set; }
        public virtual DbSet<Operator> Operator { get; set; }
        public virtual DbSet<Saha> Saha { get; set; }
        public virtual DbSet<Sirket> Sirket { get; set; }
    }
}
