//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterYonetimi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class envanterTakipWebEntities : DbContext
    {
        public envanterTakipWebEntities()
            : base("name=envanterTakipWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Depo> Depoes { get; set; }
        public virtual DbSet<Sirket_Lokasyon> Sirket_Lokasyon { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CihazTuru> CihazTurus { get; set; }
        public virtual DbSet<Islemler> Islemlers { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Lokasyon> Lokasyons { get; set; }
        public virtual DbSet<Modeller> Modellers { get; set; }
        public virtual DbSet<Modeller_Depo> Modeller_Depo { get; set; }
        public virtual DbSet<Modeller_Islemler> Modeller_Islemler { get; set; }
        public virtual DbSet<Modeller_Saha> Modeller_Saha { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<Saha> Sahas { get; set; }
        public virtual DbSet<Sirket> Sirkets { get; set; }
    }
}
