//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterYonetimi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saha
    {
        public int sahaId { get; set; }
        public string kullaniciAdi { get; set; }
        public string kullaniciSoyadi { get; set; }
        public string sirketId { get; set; }
        public string lokasyonId { get; set; }
        public string envNo { get; set; }
        public string cihazTuruId { get; set; }
        public string seriNo { get; set; }
        public string cihazModelId { get; set; }
        public string garantiBas { get; set; }
        public string durum { get; set; }
        public string islemZaman { get; set; }
        public string operatorId { get; set; }
        public string kullanim { get; set; }
        public string aciklama { get; set; }
        public string sifir_ikinci_el { get; set; }
    }
}
