
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EnvanterYonetimi.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Sirket
{

    public int sirketId { get; set; }

    public string sirket1 { get; set; }

    public string sirketNo { get; set; }

    public string kullanim { get; set; }

}

}
